[build]
  command = "npm run build:lancamento"
  publish = "dist"

[[redirects]]
  from = "/lancamento"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/lancamento/"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
